version: "3.9"

services:
  judge-server:
    image: stellarhold170nt/ptit-judge-server:latest
    container_name: judge-server
    restart: unless-stopped

    ports:
      - "2230:2230" # REST + Web UI + SOAP
      - "2240:2240" # gRPC

    volumes:
      - ./data:/app/data

    environment:
      - TZ=Asia/Ho_Chi_Minh
