<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ptit.vn/judge/soap/character"
           xmlns:tns="http://ptit.vn/judge/soap/character" elementFormDefault="qualified">
  <xs:element name="requestString">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="studentCode" type="xs:string"/>
        <xs:element name="qCode" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="requestStringResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="data" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="submitString">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="studentCode" type="xs:string"/>
        <xs:element name="qCode" type="xs:string"/>
        <xs:element name="answer" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="submitStringResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="status" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
